[package]
name = "lcms2-sys"
authors = ["Kornel Lesiński <kornel@geekhood.net>"]
build = "src/build.rs"
links = "lcms2"
repository="https://github.com/kornelski/rust-lcms2-sys.git"
readme = "README.md"
license = "MIT"
description = "Bindings for liblcms2 (Little CMS) with support for Linux, macOS, and Windows.\n\nSee lcms2 crate for a safe Rust wrapper."
include = ["src/**/*", "Cargo.toml", "README.md", "vendor/COPYING", "vendor/src/*.c", "vendor/src/*.h", "vendor/include/*.h"]
keywords = ["icc", "color", "profile", "lcms", "sys"]
categories = ["multimedia::images", "external-ffi-bindings" ]
version = "2.4.8"

[lib]
doctest = false

[build-dependencies]
cc = { optional = true, version = "1.0.3", features = ["parallel"] }
pkg-config = { optional = true, version = "0.3.9" }
dunce = "0.1.1"

[dependencies]
libc = "0.2"

[features]
default = ["dynamic", "static-fallback"]
dynamic = ["pkg-config"]
static = ["cc"]
static-fallback = ["cc"]
